//
// Created by oficus on 08.05.24.
//

#ifndef COURSEWORK_VISUAL_NOVEL_ABOUT_AUTHORS_SFML_BASIS_H
#define COURSEWORK_VISUAL_NOVEL_ABOUT_AUTHORS_SFML_BASIS_H

#endif //COURSEWORK_VISUAL_NOVEL_ABOUT_AUTHORS_SFML_BASIS_H
